version: '3.9'  # Only one version, set it to 3.9

services:
  flask:
    restart: unless-stopped
    build:
      context: ./flask  # Make sure Flask app's Dockerfile is in the ./flask directory
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          cpus: "1.0"
          memory: 512M
    ports:
      - "5000:5000"  # Exposes port 5000 for Flask
    environment:
      - REDIS_URL=redis://redis:6379/0  # Connect to the Redis container using its service name
    depends_on:
      - redis  # Ensures Redis starts before Flask

  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # Exposes Redis port 6379
    restart: unless-stopped  # Redis container will restart unless explicitly stopped
